# Generated by Django 6.1 on 2026-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('live_demo_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
